### ISSUE TITLE
Fatal bug: mods conflicts

### ISSUE THREAD

**Issue by squid233** [squid233/Elevator#1]
In version 0.1.0, there is a known bug: it conflicts with architectury.
We'll fix this bug in next version, 0.2.0.

**Comment by nephatrine** [comment]
Is 0.2.0 going to be put up on curseforge? architectury is pretty hard to avoid in a big fabric modpack.

**Comment by squid233** [comment]
Yes, I'm going to publish 0.2.0, just after fixing commands.

**Comment by squid233** [comment]
> Is 0.2.0 going to be put up on curseforge? architectury is pretty hard to avoid in a big fabric modpack.

OK, 0.2.0 has been published.
